version: "3.8"
name: chatwoot

services:
  rails:
    image: chatwoot/chatwoot:latest
    restart: always
    env_file: .env
    ports:
      - "127.0.0.1:3100:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    volumes:
      - chatwoot_storage:/app/storage

  sidekiq:
    image: chatwoot/chatwoot:latest
    restart: always
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - chatwoot_storage:/app/storage

volumes:
  chatwoot_storage:
    external: true
    name: chatwoot_chatwoot_storage
